version: '3.1'

services:
  db:
    image: docker.io/postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: bazy
    ports:
      - 5432:5432


    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
